# Generated by Django 4.2.1 on 2023-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0002_developer_genre_publisher_rating_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='Genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Battle Royale'), (4, "Beat 'em up"), (5, 'Board game'), (6, 'Co-Op'), (7, 'Competitive'), (8, 'Educational'), (9, 'Esports'), (10, 'FPS'), (11, 'Fighting'), (12, 'Horror'), (13, 'Interactive movie'), (14, 'MMO'), (15, 'Metroidvania'), (16, 'Multiplayer'), (17, 'Party'), (18, 'Platform'), (19, 'Puzzles'), (20, 'RPG'), (21, 'Racing'), (22, 'Rhythm'), (23, 'Roguelikes'), (24, 'Sandbox'), (25, 'Shooter'), (26, 'Simulation'), (27, 'Sports'), (28, 'Stealth'), (29, 'Strategy'), (30, 'Survival'), (31, 'Tactical'), (32, 'Text Based'), (33, 'Third Person Shooting'), (34, 'Tower defense'), (35, 'Turn-based'), (36, 'Visual novel'), (37, 'open world'), (38, 'Other')], default='Other', max_length=256),
        ),
    ]
