# Generated by Django 4.2.1 on 2023-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0003_remove_genre_genre_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rating',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
