# Generated by Django 4.2.1 on 2023-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0004_developer_verified_publisher_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='verified',
        ),
    ]
