# Generated by Django 4.2.1 on 2023-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0005_remove_rating_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
