# Generated by Django 4.2.1 on 2023-05-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0007_user_playlist_alter_genre_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
    ]
