# Generated by Django 4.2.1 on 2023-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePediaApp', '0008_remove_user_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='GamePediaApp.game'),
        ),
    ]
